SELECT TOP (1000) [Id]
      ,[EmpNo]
      ,[FirstName]
      ,[MiddleName]
      ,[LastName]
      ,[PhoneNumber]
      ,[EmailAddress]
      ,[Country]
      ,[DateOfBirth]
      ,[Address]
      ,[Department]
      ,[Designation]
      ,[CreatedById]
      ,[CreatedOn]
      ,[ModifiedById]
      ,[ModifiedOn]
  FROM [Employees].[dbo].[Employees]